### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by yingpaihuai** [Lorwy/WeChatPri#1]
非越狱手机
dyld: Library not loaded: /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate
  Referenced from: /var/containers/Bundle/Application/EC267A37-EB7C-4188-96F9-4BCD51AA344A/WeChatPri.app/Frameworks/libWeChatPriDylib.dylib
  Reason: image not found

**Comment by Lorwy** [comment]
你是不是没添加依赖？看MonkeyDev的wiki

**Comment by yingpaihuai** [comment]
删除otherlinks里的libsubstrate 就好了
