### ISSUE TITLE
请问做了防封防检测功能吗

### ISSUE THREAD

**Issue by FantasticSkyBaby** [Lorwy/WeChatPri#3]

**Comment by Lorwy** [comment]
做了的，特别是抢红包部分，我现在自用的就是这个微信，没有装官方微信，缺点是因为自签名的，所以无法收到消息通知

**Comment by FantasticSkyBaby** [comment]
朋友圈 还有 登录注册那块会验证bundle ID 请问这个做了吗

**Comment by Lorwy** [comment]
这个没有的，不过我一直用了这么久，没被封。。。。。估计是大号的缘故吧，哈哈
