### ISSUE TITLE
虚拟点赞功能分离问题

### ISSUE THREAD

**Issue by ruochen1989** [Lorwy/WeChatPri#4]
现有的虚拟点赞功能是通过点赞操作实现的，请问作者有没有思路把这个功能单独分离出来，然后做成可配置的方式的？求指导，谢谢

**Comment by Lorwy** [comment]
这个其实很简单的，在设置界面自己加个开关就行了

**Comment by ruochen1989** [comment]
你好，大佬，可以留个联系方式交流技术吗？群组或其他方式均可
