### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by xPotatoBoy** [Lorwy/WeChatPri#5]
Hi can you write a guide on how to compile? When I open the project and try to compile it (MacOs High Sierra) it gives so many errors.

您好 这个下载之后怎么用？可不可以写个教程 谢谢

**Comment by Lorwy** [comment]
基于MonkeyDev的，你先按照其wiki安装好环境就OK了
https://github.com/AloneMonkey/MonkeyDev
